name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-phar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xdebug
          coverage: none

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build PHAR
        run: vendor/bin/box compile

      - name: Rename PHAR with version
        run: |
          VERSION=$(jq -r .version composer.json)
          mv phpseq.phar phpseq-$VERSION.phar

      - name: Upload PHAR to Release
        uses: softprops/action-gh-release@v1
        with:
          files: phpseq-*.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
