@startuml components
title go54-api communications
skinparam componentStyle rectangle
skinparam wrapWidth 220
skinparam shadowing false
hide stereotype

component "go54-api
(1029 classes)" as C_475b3921

C_475b3921 --> C_475b3921 : 2406 calls
caption Generated on 2025-09-09 16:54:40
@enduml
